Jenkinsfile

diff --git a/dev/lifecycle/debian b/dev/lifecycle/debian
--- a/dev/lifecycle/debian
+++ b/dev/lifecycle/debian
@@ -4,6 +4,7 @@ set -eu
 trap exit INT TERM
 
 VERSION=""
+SOURCE=""
 TARGET_ARCHITECTURE=""
 
 while [ $# -gt 0 ] ; do
@@ -11,13 +12,19 @@ key="$1"
 
 case $key in
 
+  --source)
+    SOURCE="$2"
+    shift
+    shift
+  ;;
+
   --arch)
     TARGET_ARCHITECTURE="$2"
     shift
     shift
   ;;
 
-  -v|--version)
+  --version)
     VERSION="$2"
     shift
     shift
@@ -30,14 +37,47 @@ case $key in
 esac
 done
 
-if [ ! "${VERSION}" ] ; then
+if [ -z "${VERSION}" ] ; then
   (>&2 echo "version not provided")
   exit 1
 fi
 
-if [ ! "${TARGET_ARCHITECTURE}" ] ; then
+if [ -z "${SOURCE}" ] ; then
+  (>&2 echo "source not provided")
+  exit 1
+fi
+
+if [ -z "${TARGET_ARCHITECTURE}" ] ; then
   (>&2 echo "target architecture not provided (use e.g. --arch amd64)")
   exit 1
+fi
+
+
+
+DEB_SOURCES="${SOURCE}/debian_${TARGET_ARCHITECTURE}"
+BIN_SOURCES="${SOURCE}/bin"
+
+if [ ! -d "${DEB_SOURCES}" ] ; then
+  (>&2 echo "packaging for ${TARGET_ARCHITECTURE} is not supported")
+  exit 1
+fi
+
+if [ ! -f "${BIN_SOURCES}/ledger-rest-linux-${TARGET_ARCHITECTURE}" ] ; then
+  (>&2 echo "did not found binary to package at ${BIN_SOURCES}/ledger-rest-linux-${TARGET_ARCHITECTURE}")
+  exit 1
+fi
+
+if [ ! -f "${BIN_SOURCES}/ledger-unit-linux-${TARGET_ARCHITECTURE}" ] ; then
+  (>&2 echo "did not found binary to package at ${BIN_SOURCES}/ledger-unit-linux-${TARGET_ARCHITECTURE}")
+  exit 1
+fi
+
+mkdir -p ${DEB_SOURCES}/usr/bin
+if [ -f "${DEB_SOURCES}/usr/bin/ledger-rest" ] ; then
+  rm -f ${DEB_SOURCES}/usr/bin/ledger-rest
+fi
+if [ -f "${DEB_SOURCES}/usr/bin/ledger-unit" ] ; then
+  rm -f ${DEB_SOURCES}/usr/bin/ledger-unit
 fi
 
 generate_manpage() {
@@ -175,33 +215,6 @@ check_files() {
 
 ################################################################################
 
-PKGS="$(pwd)/packaging"
-DEB_SOURCES="${PKGS}/debian_${TARGET_ARCHITECTURE}"
-BIN_SOURCES="${PKGS}/bin"
-
-if [ ! -d "${DEB_SOURCES}" ] ; then
-  (>&2 echo "packaging for ${TARGET_ARCHITECTURE} is not supported")
-  exit 1
-fi
-
-if [ ! -f "${BIN_SOURCES}/ledger-rest-linux-${TARGET_ARCHITECTURE}" ] ; then
-  (>&2 echo "did not found binary to package at ${BIN_SOURCES}/ledger-rest-linux-${TARGET_ARCHITECTURE}")
-  exit 1
-fi
-
-if [ ! -f "${BIN_SOURCES}/ledger-unit-linux-${TARGET_ARCHITECTURE}" ] ; then
-  (>&2 echo "did not found binary to package at ${BIN_SOURCES}/ledger-unit-linux-${TARGET_ARCHITECTURE}")
-  exit 1
-fi
-
-mkdir -p ${DEB_SOURCES}/usr/bin
-if [ -f "${DEB_SOURCES}/usr/bin/ledger-rest" ] ; then
-  rm -f ${DEB_SOURCES}/usr/bin/ledger-rest
-fi
-if [ -f "${DEB_SOURCES}/usr/bin/ledger-unit" ] ; then
-  rm -f ${DEB_SOURCES}/usr/bin/ledger-unit
-fi
-
 case ${TARGET_ARCHITECTURE} in
 
   armhf)
@@ -246,10 +259,10 @@ case ${TARGET_ARCHITECTURE} in
   *)
     cp \
       "${BIN_SOURCES}/ledger-rest-linux-${TARGET_ARCHITECTURE}" \
-      "${DEB_SOURCES}/usr/bin/ledger-unit"
-    cp \
-      "${BIN_SOURCES}/ledger-rest-linux-${TARGET_ARCHITECTURE}" \
       "${DEB_SOURCES}/usr/bin/ledger-rest"
+    cp \
+      "${BIN_SOURCES}/ledger-unit-linux-${TARGET_ARCHITECTURE}" \
+      "${DEB_SOURCES}/usr/bin/ledger-unit"
   ;;
 
 esac
diff --git a/dev/lifecycle/package b/dev/lifecycle/package
--- a/dev/lifecycle/package
+++ b/dev/lifecycle/package
@@ -5,12 +5,13 @@ trap exit INT TERM
 
 TARGET_ARCHITECTURE="linux/amd64"
 TARGET_PACKAGE=""
+OUTPUT=""
 
 package_service() {
-  local working_dir=/go/src/github.com/jancajthaml-openbank/${TARGET_PACKAGE}
+  local working_dir=${GOPATH}/src/github.com/jancajthaml-openbank/${TARGET_PACKAGE}
   local arch=${TARGET_ARCHITECTURE#*/}
   local platform=${TARGET_ARCHITECTURE%%/*}
-  local output=$(pwd)/packaging/bin/${TARGET_PACKAGE}-${platform}-${arch}
+  local output=${OUTPUT}/${TARGET_PACKAGE}-${platform}-${arch}
 
   if [ -f ${output} ] ; then
     rm -f ${output}
@@ -97,6 +98,12 @@ case $key in
     shift
   ;;
 
+  --output)
+    OUTPUT="$2"
+    shift
+    shift
+  ;;
+
   *)
     shift
   ;;
@@ -104,8 +111,13 @@ case $key in
 esac
 done
 
-if [ ! "${TARGET_PACKAGE}" ] ; then
+if [ -z "${TARGET_PACKAGE}" ] ; then
   (>&2 echo "[error] target package not provided")
+  exit 1
+fi
+
+if [ -z "${OUTPUT}" ] ; then
+  (>&2 echo "[error] output not provided")
   exit 1
 fi
 
